---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: observability
spec:
  repo: https://grafana.github.io/helm-charts
  chart: loki
  version: 6.10.2
  targetNamespace: observability
  valuesContent: |
    loki:
      schemaConfig:
        configs:
          - from: 2024-01-01
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      ingester:
        chunk_encoding: snappy
      tracing:
        enabled: true
      querier:
        max_concurrent: 4
      storage:
        type: s3
        bucketNames:
          chunks: "chunks"
          ruler: "ruler"
          admin: "admin"
        s3:
          s3: s3://ceph-rook-cluster.ceph-rook/loki
          endpoint: loki
          s3ForcePathStyle: false
          insecure: false
          http_config: {}
    deploymentMode: SimpleScalable
    backend:
      replicas: 3
    read:
      replicas: 3
    write:
      replicas: 3
    minio:
      enabled: false
    singleBinary:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
