---
apiVersion: v1
kind: Namespace
metadata:
  name: openbao
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: openbao
  namespace: openbao
spec:
  repo: https://openbao.github.io/openbao-helm
  chart: openbao
  version: 0.4.0
  targetNamespace: openbao
